# Generated by Django 5.1.3 on 2024-11-08 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='course',
        ),
        migrations.RemoveField(
            model_name='student',
            name='mentername',
        ),
        migrations.AddField(
            model_name='student',
            name='activity',
            field=models.CharField(choices=[('course', 'Course'), ('internship', 'Internship'), ('project', 'Project')], default='course', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='activity_endtdate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='activity_startdate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='mentorname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='hours',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='studentname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
