# Generated by Django 5.1.3 on 2024-11-08 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_student_course_remove_student_mentername_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='hours',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
