# Generated by Django 5.1.3 on 2024-11-08 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_student_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='hours',
            field=models.TimeField(null=True),
        ),
    ]
