# Generated by Django 5.1.3 on 2024-11-09 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_student_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='hours',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
