# Generated by Django 5.1.3 on 2024-11-09 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_student_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='date',
        ),
    ]
