# Generated by Django 5.1.3 on 2024-11-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_customuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='activity_endtdate',
        ),
        migrations.AddField(
            model_name='student',
            name='college_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='mobilenumber',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='subject',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='activity',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
