# Generated by Django 5.1.3 on 2024-11-14 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_student_activity_endtdate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='activity',
            new_name='collegeName',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='activity_startdate',
            new_name='joiningDate',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='college_name',
            new_name='mentor',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='mentorname',
            new_name='program',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='mobilenumber',
            new_name='programType',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='studentname',
            new_name='studentName',
        ),
        migrations.RemoveField(
            model_name='student',
            name='hours',
        ),
        migrations.RemoveField(
            model_name='student',
            name='subject',
        ),
        migrations.AddField(
            model_name='student',
            name='courseDuration',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='mobileNumber',
            field=models.IntegerField(null=True),
        ),
    ]
