# Generated by Django 5.1.3 on 2024-11-14 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_rename_activity_student_collegename_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSyllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('activity', models.CharField(max_length=100, null=True)),
                ('mentor', models.CharField(max_length=100, null=True)),
                ('hour', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='studentcoursedetails',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
