# Generated by Django 5.1.3 on 2024-11-14 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_studentsyllabus_student_studentcoursedetails_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsyllabus',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.student'),
        ),
    ]
